######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 21 21:19:49 2013
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += ..
INCLUDEPATH += ..

# Input
HEADERS += ../data.hh \
           ../datadispatch.hh \
           ../datafile.hh \
           ../dynindvector.hh \
           ../format.hh \
           ../formatbinary.hh \
           ../formatcont.hh \
           ../formatdiscr.hh \
           ../formatdispatch.hh \
           ../formatsymbol.hh \
           ../formattime.hh \
           ../formattypes.hh \
           ../formatunknown.hh \
           ../growable.hh \
           ../hashtable.hh \
           ../intfloat.hh \
           ../readtokens.hh \
           ../sorteddynindvector.hh \
           ../sortedhashtable.hh \
           ../table.hh

SOURCES += ../data.cc \
           ../datadispatch.cc \
           ../datafile.cc \
           ../format.cc \
           ../formatbinary.cc \
           ../formatcont.cc \
           ../formatdiscr.cc \
           ../formatdispatch.cc \
           ../formatsymbol.cc \
           ../formattime.cc \
           ../formatunknown.cc \
           ../readtokens.cc \
           ../table.cc

QMAKE_CXXFLAGS += -Wno-unused -Wno-uninitialized
