#! /bin/sh

# These warnings are not supported in g++ 4.2
WARNINGS44="-Wlogical-op -Wmissing-declarations"

# "uname -o" doesn't exist on Darwin.
OS=`uname`
if [ "$OS" = "Darwin" ];
then
    WARNINGS44=
    XCXXFLAGS="-DPLATFORM_MAC"
elif [ `expr substr $OS 1 6` = "CYGWIN" ];
then
    WARNINGS44=
    XCXXFLAGS="-DPLATFORM_MSW"
elif [ "$OS" = "Linux" ];
then
    WARNINGS44="-Wmissing-declarations"
    XCXXFLAGS="-DUSE_WCHAR -DPLATFORM_GTK"
elif [ "$OS" = "FreeBSD" ];
then
    WARNINGS44=
    XCXXFLAGS="-DPLATFORM_GTK"
else
    echo "Error: unknown platform $OS - modifying our-g++ may help"
    exit 1
fi

CXX=g++
#CXX=clang++
#CXX=/home/arndt/clang/llvm-3.3.src/Release+Asserts/bin/clang++

CXXFLAGS="-DGZLIB -Wall -Wno-write-strings -Wextra -Wno-unused-parameter -Wmissing-noreturn -Wshadow -Wswitch-default $WARNINGS44 -g $XCXXFLAGS"

# Sometimes interesting: -O -fdiagnostics-show-option
# -O causes more semantic analysis to be done, so we may get more warnings

# -Wredundant-decls -Waggregate-return -Wunreachable-code react to wx.h

# -Wfloat-equal and -Wconversion triggers warnings in wx

# -Winline together with -O give a lot of warnings from wxWidgets

#echo $CXX $CXXFLAGS $@
if [ "$OS" = "Darwin" ];
then
# Mac OS: wxWidgets or others may not be compiled for 64 bits architecture
#    $CXX  -m32 $CXXFLAGS $@
    $CXX $CXXFLAGS $@
else
    $CXX $CXXFLAGS $@
fi
